### ISSUE TITLE
Konnector for Orange bills

### ISSUE THREAD

**Issue by eravion** [cozy-labs/konnectors#101]
I have an account and I can help.
But I don't have the knowledge to develop ...

**Comment by frankrousseau** [comment]
Hello @eravion, could you send me a private message on the forum with your credentials?

**Comment by eravion** [comment]
done by email not by forum message

**Comment by frankrousseau** [comment]
Orange konnector was added. Could you tell me if it works for you?

**Comment by eravion** [comment]
Hello,

Yes, the download of invoice is ok, thanks, good job :)
The match with Kresus is not working, I don't know if it is normal ?

**Comment by frankrousseau** [comment]
No it isn't :). Could you give me the label of the bank operation and the number of day between the invoice date and the bank operation date?

**Comment by eravion** [comment]
Hi,
Kresus Informations
Label: PRLV SEPA ORANGE ECH/070715 ID EMETTEUR/FRXXYYYZZZ
Amount: -30.03

Pdf Informations
Date of Invoice : votre facture du 26 juin 2015
Text inside the PDF : montant prélevé automatiquement le 06/07/2015
Amount : 30,03

**Comment by eravion** [comment]
Hi

It works now.
Thanks :)

**Comment by frankrousseau** [comment]
Great!
