### ISSUE TITLE
Konnector for SFR

### ISSUE THREAD

**Issue by eravion** [cozy-labs/konnectors#102]
I have credential to help ...

**Comment by frankrousseau** [comment]
Hello @eravion, could you send me a private message on the forum with your credentials?

**Comment by doubleface** [comment]
I think this one is done by 7900c04be743108a592444c906810e5c463372ae and then it can be closed.

**Comment by frankrousseau** [comment]
@eravion can you confirm it works for you?

**Comment by eravion** [comment]
Hello,
I don't have credential to test, I provided one for the development, but I can't use it today.
Sorry, I cannot confirm.

**Comment by frankrousseau** [comment]
Let's close this one. Thank you again @doubleface for the connector.
