### ISSUE TITLE
Twitter konnector HTML issue

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#105]
When using the Twitter konnector, I can see a small HTML markup issue : 

Vous pouvez les générer via le href="https://apps.twitter.com/">tableau Twitter de gestion d'applications

**Comment by cylwin** [comment]
Hi,

Thank you for the report, fixed in https://github.com/cozy-labs/konnectors/commit/963a9a804100d7ce57ee62c15244c868e8d053c8

Bye
