### ISSUE TITLE
Konnectors Github commits: wrong number of imported commits

### ISSUE THREAD

**Issue by jsilvestre** [cozy-labs/konnectors#110]
Every time the connector runs, the notifications states the same number of commits (if it has not changed in the meantime). I believe the number is the commits found, not those actually imported (which matters because of duplicates).

**Comment by frankrousseau** [comment]
I think the konnector was broken. You probably have many duplicates of commits :/. I will work on a fixing patch soon. 
Can you try again and tells me if the number is still wrong?

**Comment by frankrousseau** [comment]
I close that one because I don't have any news from the bug reporter. @jsilvestre feel free to open it again if needed.
