### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Mistress-Anna** [cozy-labs/konnectors#117]
There should be a LICENSE.txt or COPYING.txt for a quick view. Currently there only seems to be an indication in packages.json, which is only for people who know the framework, and also know the license is in this file. Additionally, there's no version number of the license.

**Comment by frankrousseau** [comment]
Thank you @Mistress-Anna for your feedback about the licens. The license file will be added in the next release (0.3.4).

**Comment by nono** [comment]
The license is now here: https://github.com/cozy-labs/konnectors/blob/master/LICENSE.

@frankrousseau I think you can close this issue.

**Comment by frankrousseau** [comment]
Yep thank you @nono and @Mistress-Anna
