### ISSUE TITLE
Default logo for new connectors

### ISSUE THREAD

**Issue by nono** [cozy-labs/konnectors#122]
Each connector has a logo on the webapp. For DigitalOcean and Sosh, the logo is not in the sprite and fallback to the first one (Bouygues in my case). It should be nice to have a default logo for connectors instead of showing the Bouygues logo for Sosh.

**Comment by ZeHiro** [comment]
Hello, you should update the app (even if you were not notified to), or reinstall it. This topic was closed without a raise in the version number. Should be fixed here: 

https://github.com/cozy-labs/konnectors/issues/99

**Comment by nono** [comment]
I confirm, it's fixed.
