### ISSUE TITLE
Can't change folder in Sosh konnector

### ISSUE THREAD

**Issue by nledez** [cozy-labs/konnectors#125]
I create a new folder for my Sosh bills.

But when I change the drop down list and click on "Save and import " the choice is lost.

**Comment by ZeHiro** [comment]
There seem to be exaclyt the same problems with other konnectors (free and free mobile). But it seems to be just "visual" (ie the change is saved in the DB)

**Comment by frankrousseau** [comment]
It will be fixed in the upcoming 0.4.0 version.

**Comment by frankrousseau** [comment]
It's fixed @nledez, can you confirm

**Comment by frankrousseau** [comment]
I close that one because I don't have any news from the bug reporter. @nledez  feel free to open it again if needed.

**Comment by nledez** [comment]
It's look like good. Thanks.
