### ISSUE TITLE
Wrong link for "open selected folder" by default for unconfigured konnectors

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#131]
When using a konnector which allows to select a folder, the default selected folder is the first in the lexical order. However, unless I manually select a folder in the dropdown, the link of "open selected folder" is wrong (redirects to "https://demo.cozycloud.cc/#apps/files/folders/") since it does not include the folder id.

This only happens with konnectors which are not yet configured !

**Comment by frankrousseau** [comment]
It should be fixed. Can you update the application and try again?

**Comment by nicofrand** [comment]
I tried on the demo and everything seems Ok now !

**Comment by frankrousseau** [comment]
Great, thank you!

**Comment by nicofrand** [comment]
It looks like it does not work anymore on the demo since the last version (0.4.1) ?
