### ISSUE TITLE
Update request-json dependency

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#133]
Konnectors should upgrade its request-json dependency to the latest version ([or at least 0.5.1](https://github.com/cozy/request-json/commit/5583cc206e5ec45303e9eba131d3c14e493ef2dd)) to be able to use the `createClient` instead of the `newClient` method as stated in the [documentation](https://github.com/cozy/request-json/blob/master/README.md).

**Comment by frankrousseau** [comment]
Done here: https://github.com/cozy-labs/konnectors/commit/257b6c0f6e6d76adb0784b624babb8cc4e317f78 !

Thank you for reporting!
