### ISSUE TITLE
Duplicate files for Free & Free Mobile bills

### ISSUE THREAD

**Issue by nono** [cozy-labs/konnectors#141]
Hello,

I have updated konnectors to the 0.4.1 version and bills from Free an Free Mobile are duplicated:

![screen shot 2015-08-21 at 12 10 47](https://cloud.githubusercontent.com/assets/2767/9406124/c9bbb0f2-47fd-11e5-9f88-72d9bb0467de.png)

Is it expected?

**Comment by frankrousseau** [comment]
Not at all. It's probably a bug with my recent changes. It checks if the file exists and if not it creates it.

**Comment by ZeHiro** [comment]
For freemobile, if you have multiple lines, it is normal, it does not make the différence bewee' all lines. I have an update of the konnector. I'll push it after my holidays

**Comment by frankrousseau** [comment]
I can't reproduce for the the free bills. I don't know where to start. Can you remove all your bill files and bill data about free. Then can you fetch them again several times?

**Comment by nono** [comment]
I've removed the bills, and launched several imports. There are no duplicates.

Maybe, for a given file, one duplicate was with an old version of konnector and the other with a recent version of konnector.

**Comment by nono** [comment]
@frankrousseau same for Free Mobile. Starting from an empty directory, it works fine.

@ZeHiro I have 2 lines. After deleting the files and launched several imports, I have now 2 files for each month:

- `<year><month>_freemobile.pdf` (the bill of one line)
- `<year><month>_freemobile_.pdf` (the sumarry)

But, in the screenshot, you can see that the exact same file was duplicated.

**Comment by frankrousseau** [comment]
Ok it doesn't sound good but if it now works let it that way. I let the @ZeHiro answer for the freemobile issues.

Thank you again for reporting.

**Comment by ZeHiro** [comment]
For the wired names, it is a bug, which will be fixed in the net update of the konnector. The number of the line will be included for the line bills. No number for the overall bill. PR for september.

**Comment by ZeHiro** [comment]
The bug is fixed normally. And I confirm the bug for free mobile and free konnectors, but it is reimported once.

**Comment by frankrousseau** [comment]
@nono what is the state of this issue?

**Comment by nono** [comment]
It's okay for me now. It was just one version of konnectors which created duplicate files.
