### ISSUE TITLE
Disable buttons for which answer from the server is required. Mostly "save and import button"

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#146]
From forum user : 

https://forum.cozy.io/t/konnectors-probleme-dimportation-des-pdf-free-mobile/1074/27

It is possible to send twice the import request if a second import is launched between the first request, and the answer of the server "isImporting = true". 
This leads to 2 concurring imports
This problem can be abserved mainly on the freemobile konnector, as it detects the presence of the form to detect if the connection is succesful (The server ALWAYS answers "302 + location set to index.php?page=home" wether the connection was succesful or not)

**Comment by nicofrand** [comment]
That should already be the case: https://github.com/cozy-labs/konnectors/blob/master/client/app/views/konnector.coffee#L181

**Comment by ZeHiro** [comment]
https://github.com/cozy-labs/konnectors/blob/master/client/app/views/konnector.coffee#L95

the button should have disabled=true also

**Comment by nicofrand** [comment]
Yep, and no need to reparse the DOM each time, we can chain the requests: `.attr(a,b).attr(a,b)`.
I'll do it.
