### ISSUE TITLE
Missing french translations

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#148]
Hi,

here are some missiing french translations: 

- "open selected folder" (konnector view)
- "Select a starting date" (konnector view when automatic import is set to "every week/month")
- "From" (konnector view when automatic import is set to "every week/month")

**Comment by frankrousseau** [comment]
Thank @ZeHiro for reporting.

**Comment by babolivier** [comment]
Fixed in PR #155, maybe this issue can be closed now?

**Comment by frankrousseau** [comment]
Thank you @babolivier
