### ISSUE TITLE
Some konnectors do not say they fail

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#163]
Several konnectors, when provided with wrong id/passwords do not say they failed or even that no importation was done, but just say "Last import: date" (whereas they did not import anything).

It is the case for:

- [ ] Numéricable
- [ ] Bouygues Box
- [ ] Bouygues Télécom
- [ ] Github
- [ ] Jawbone
- [ ] Orange
- [ ] Sosh

**Comment by nicofrand** [comment]
I do not know for *Nest* but the konnector appears as it is still loading whereas there is an error in the logs.

**Comment by frankrousseau** [comment]
Errors are not properly managed with Konnectors. We must fix it. Thank you for reporting @nicofrand.

**Comment by nicofrand** [comment]
Warning: some of the konnectors do say they failed, or at least they say "Pas d'importation effectuée" like *Free* and *Free mobile* for example.

**Comment by frankrousseau** [comment]
@nicofrand Do you still face that issue?

**Comment by nicofrand** [comment]
Yep. I checked again with Orange for example by providing wrong id and passwords. I expect it to say "Wrong id/password" but instead it just shows the last import date, as if everything went well.

**Comment by frankrousseau** [comment]
OK thank you!

**Comment by nicofrand** [comment]
Same as https://github.com/cozy-labs/konnectors/issues/267 (which is more exhaustive).
