### ISSUE TITLE
Orange konnector fails silently if password was updated

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#165]
As [reported](https://forum.cozy.io/t/konnector-pb-avec-changement-pwd/1691) by @eravion: he changed it's password, so the connector was unable to connect, but didn't throw any error.

**Comment by clochix** [comment]
@Peltoche any news on this?

**Comment by Peltoche** [comment]
I juste received the identifier/password so now I will be able to work on it.

**Comment by Peltoche** [comment]
This PR should solve this issue:  https://github.com/cozy-labs/konnectors/pull/168
