### ISSUE TITLE
[Twitter] Open Twitter application manager in a new tab

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#172]
To get Twitter credentials, we open https://apps.twitter.com/ This page send an `X-Frame-Option` header that prevent opening it inside an iframe. So when we click on the link, we just get a blank page. We should add a `target="_blank"` to open the page in a new tab.

I opened this issue instead of fixing it myself because I think we should also explain what to do on the Twitter application list: click on the button to create a new application, then explain how to fill the form.

**Comment by frankrousseau** [comment]
I fixed the link. About the explanation, let's see if someone mentions the problem.

**Comment by frankrousseau** [comment]
Thank you for reporting.
