### ISSUE TITLE
Disallow HTML messages from konnectors

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#188]
When a konnector returns an error message (or any other message) containing HTML, [this HTML is displayed as it is in the user interface](https://github.com/cozy-labs/konnectors/blob/da9cc8efc4213a6a8c292c7cbb1c5cd979105fd6/client/app/views/konnector.coffee#L90). 

A konnector is then able to do anything (like a [meta redirection](https://github.com/cozy-labs/konnectors/issues/186)) and break the application.

IMO, a konnector should only be able to return a simple string and that string should be cleaned for **security reasons** and also because only the application should decide of the design, not a single konnector.

If the error message for example is `<b>Error</b>` the HTML code should become `&lt;b&gt;Error&lt;/b&gt;`.

**Comment by clochix** [comment]
Thanks for reporting @nicofrand, we'll try to fix this quickly !

**Comment by nicofrand** [comment]
I think this was solved by commit [a88f8d8afae1f383b6af3dd54933b86059f4c7ab](https://github.com/cozy-labs/konnectors/commit/a88f8d8afae1f383b6af3dd54933b86059f4c7ab) and then with the next [build](https://github.com/cozy-labs/konnectors/commit/0df8bcf9d2232a20d33da3b5752a9ed93b1970fb), I close the issue.
