### ISSUE TITLE
Missing dependancies in package.json

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#189]
At least : 
brunch 
babel

are missing in the dev dependancies.

**Comment by nicofrand** [comment]
For the development branch at least.

**Comment by clochix** [comment]
Thanks for reporting!
@Peltoche, are you still around there?

**Comment by Peltoche** [comment]
Hi! This modules need to be installed globally, they are the main tools used in almost all nodejs projects so it seem a bad practice to install them locally in all projects.

you can make:
```
[sudo] npm install -g brunch babel
```

**Comment by nicofrand** [comment]
Yeah, I can install it globally, but the package.json should declare them too, right ? They won't be installed locally if they already are installed globally, but at least they'll be installed if needed.

**Comment by ZeHiro** [comment]
looking at the build script, they need to be installed locally: 
https://github.com/cozy-labs/konnectors/blob/development/scripts/build.sh#L5
https://github.com/cozy-labs/konnectors/blob/development/scripts/build.sh#L25

**Comment by nono** [comment]
The [build script](https://github.com/cozy-labs/konnectors/blob/development/scripts/build.sh) clearly expects that brunch and babel are installed locally and globally (`node_modules/.bin` is only for local npm packages).

For brunch, it's already in the [package.json](https://github.com/cozy-labs/konnectors/blob/development/client/package.json) for the client. It is installed on step 2 of 3 in [build section of the readme](https://github.com/cozy-labs/konnectors#build).

For babel, it's a bug.

**Comment by nono** [comment]
Oh, the step 2 has been removed in the development branch.

**Comment by frankrousseau** [comment]
Thank you @nono it's now fixed.
