### ISSUE TITLE
Date switch to american format

### ISSUE THREAD

**Issue by genma** [cozy-labs/konnectors#192]
In Konnectors, I try to import my Github commits or Linkedin contacts. In the date selector, I can select the current date "11-02-2016 (11 february 2016, in French). When I click on "Save & import button", import doesn't work. And the date automatically switch to an american format. So the selected date become 02 november 2016 (in calendar) and appears as "02-11-2016" in field.

**Comment by clochix** [comment]
Thanks for reporting @genma !

**Comment by nicofrand** [comment]
Where do you select the date ? Maybe that feature has been removed ? I don't see it :/.

**Comment by ZeHiro** [comment]
@nicofrand It was possible to select the date of the first import, in case of weekly/monthly imports. The function was removed.
