### ISSUE TITLE
Bill/operation match not done

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#206]
From last update (or previous one) : 0.4.10/11, the match between operations and bills it not done anymore. 
Here is my date setting on my configuration, because from previous analysis, it is due to problems in managing the UTC/GMT differences: 
``
cozy-term@cozy:~$ date

Tue Mar  8 14:09:01 CET 2016
``
From previous analysis, the involved pieces of code where these one: 
- https://github.com/cozy-labs/konnectors/blob/master/server/lib/link_bank_operation.coffee#L84
If the entry was saved in "local time" ie not UTC, not entry will be retreived
- https://github.com/cozy-labs/konnectors/blob/master/server/lib/save_data_and_file.coffee#L43
The entry.date should be normalized :
``` coffeescript
 entry.date = "#{entry.date.format('YYYY-MM-DD')}T00:00:00.000Z"
```

**Comment by frankrousseau** [comment]
It looks fixed by @ZeHiro.
