### ISSUE TITLE
Konnector view not rerendered on fields update serverside

### ISSUE THREAD

**Issue by babolivier** [cozy-labs/konnectors#212]
I'm trying to use the "OVH EU" konnector. I select the folder to import into, and click "Save and Import" and get an error: "You need to login to your OVH account first."
No login link, nowhere to enter my credentials.

**Comment by frankrousseau** [comment]
Yep, it fails for me too. Normally a special link should be displayed. I don't understand why it doesn't appear in prod mode.

**Comment by Chocobozzz** [comment]
Same here. Don't understand too. I investigate.

**Comment by Chocobozzz** [comment]
@frankrousseau These lines seem to be responsible for this issue: https://github.com/cozy-labs/konnectors/blob/master/client/app/models/konnector.coffee#L13

**Comment by frankrousseau** [comment]
Arg yes my bad. It shouldn't delete it. They just need to be ignored by the comparison.

**Comment by ZeHiro** [comment]
@Chocobozzz @babolivier 
Is this working now?

**Comment by Chocobozzz** [comment]
In my side yes, but the link is not displayed in real time. We need to click on another konnector and then re click on OVH to see it. I don't think it was the case before.

**Comment by ZeHiro** [comment]
@Chocobozzz I cannot see the link either (impossible to create the connector). Seems like the ui was cleaned up a bit :s

**Comment by nicofrand** [comment]
As @Chocobozzz said, the konnector does work (as it fetches the bills). The issue is only that the link is not displayed just after the import, the user has to click on another connector and then come back to the OVH connector to see it.

**Comment by nicofrand** [comment]
Related but not the root of the issue: looks like the fields loginUrl and token are not translated.

> WARNING: Missing translation for key: "loginUrl"vendor.js:1:228214
WARNING: Missing translation for key: "token"

**Comment by ZeHiro** [comment]
https://github.com/cozy-labs/konnectors/blob/master/client/app/realtime.coffee#L27
Realtime Should also update konnector fields

**Comment by ZeHiro** [comment]
+ the translation for hidden inputs shouldn't be done
