### ISSUE TITLE
Connection to ameli fail

### ISSUE THREAD

**Issue by encolpe** [cozy-labs/konnectors#216]
From the log:

```
[Fri, 18 Mar 2016 23:57:42 GMT] - PUT /konnectors/a87eb666a966bccd4b389963e9a5f1a1 - 200 - 54.395 ms -  16
[2016-03-19 00:57:42:977] info - ameli : Next update 26/03/2016 at 00:57:42

/usr/local/cozy/apps/konnectors/build/server/konnectors/ameli.js:59
        'Cookie': res.headers['set-cookie'],
                     ^
TypeError: Cannot read property 'headers' of undefined
    at Request._callback (/usr/local/cozy/apps/konnectors/build/server/konnectors/ameli.js:59:22)
    at self.callback (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:198:22)
    at Request.emit (events.js:95:17)
    at Request.onRequestError (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:820:8)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1384:19)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:977:10)
```

**Comment by jeekajoo** [comment]
Same here. Let me know if you need more info.

**Comment by frankrousseau** [comment]
ping @Gara64

**Comment by frankrousseau** [comment]
Thank you @encolpe  and @jeekajoo for reporting.

**Comment by Gara64** [comment]
It looks like the first GET request to ameli fails, but I cannot figure out why, and I can't reproduce.
@encolpe and @jeekajoo , do you have others konnectors working? 
And to be sure everything is correctly set up, could you uninstall the app then reinstall and retry?
By this time I'll handle this error to have more logs.
Thanks!

**Comment by encolpe** [comment]
I have the same problem with LinkedIn, but Free, Online and Orange connectors are working.

**Comment by jeekajoo** [comment]
all other konnectors I have work, uninstalling / reinstalling did not help.

**Comment by jeekajoo** [comment]
with version 0.5.3: `An error occurred during the last import: CERT_UNTRUSTED`

**Comment by Gara64** [comment]
Thanks @encolpe and @jeekajoo, and sorry for the delay. So it's apparently a debian certificate error. Were you able to fix it? I tried with an up-to-date debian jessie, and it worked for me.
Otherwise, not sure it's related, but I made a patch as suggested [here](https://github.com/request/request/issues/811). You can try it by re-installing Konnector throught this [repo](https://github.com/Gara64/konnectors), on the branch 'ameli'. You can do it by copy-pasting this url below your cozy's store : https://github.com/Gara64/konnectors.git@ameli

**Comment by frankrousseau** [comment]
I think there is an option in request to accept untrusted certificates.

**Comment by Gara64** [comment]
@frankrousseau yes, we can use `strictSSL: false`, but I prefer to avoid this if possible :)

**Comment by jeekajoo** [comment]
> I tried with an up-to-date debian jessie, and it worked for me.

Well, can you show me the result of `dpkg -l | grep ca-certificates` ?
I would be surprised you have version 20141019+deb8u1

One temp solution would be to use the older version of the Mozilla bundle that includes removed trust bits for RSA-1024 keys : https://raw.githubusercontent.com/bagder/ca-bundle/e9175fec5d0c4d42de24ed6d84a06d504d5e5a09/ca-bundle.crt

```bash
echo GET | openssl s_client -connect assure.ameli.fr:443 -CAfile ca-bundle.crt | grep "Verify return code"
depth=3 C = ZA, ST = Western Cape, L = Cape Town, O = Thawte Consulting cc, OU = Certification Services Division, CN = Thawte Premium Server CA, emailAddress = premium-server@thawte.com
verify return:1
depth=2 C = US, O = "thawte, Inc.", OU = Certification Services Division, OU = "(c) 2006 thawte, Inc. - For authorized use only", CN = thawte Primary Root CA
verify return:1
depth=1 C = US, O = "thawte, Inc.", OU = Domain Validated SSL, CN = thawte DV SSL CA - G2
verify return:1
depth=0 CN = assure.ameli.fr
verify return:1
DONE
    Verify return code: 0 (ok)
```
... or use `strictSSL: false`. Ameli TLS security is shit by the way: https://twitter.com/jeekajoo/status/715512087397707776

References:
http://stackoverflow.com/questions/22973701/ssl-errors-using-mailchimps-api/29649024#29649024
http://forums.debian.net/viewtopic.php?f=5&t=126723
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812488
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819108

**Comment by encolpe** [comment]
I tried to upgrade to stretch version and downgrade to wheezy version without success (http://ftp.debian.org/debian/pool/main/c/ca-certificates/).
As it is a Debian bug, we can close it here.

**Comment by clochix** [comment]
Another user [report this problem](https://forum.cozy.io/t/konnectors-propositions-petit-prob-dimport/2303) : « Une erreur est survenue lors de la dernière importation : CERT_UNTRUSTED »

**Comment by Gara64** [comment]
@jeekajoo @encolpe Sorry again for the delay, I've been busy with work and medical stuff :)
I do have the `20141019+deb8u1` version, and I have the same warning with `curl`, but not with `request`, oddly. Anyway, I made a [patch](https://github.com/cozy-labs/konnectors/pull/227) to add `strictSSL: false` by the meantime this is solved on Debian.
Please let me know if it works for you!

**Comment by encolpe** [comment]
I prefer a **strictSSL: true** as services should have a valid SSL certificate. Again, it's a debian bug. Don't break the security for it.

**Comment by jeekajoo** [comment]
Looks like it is now able to connect. (but I'm now stuck here: #236 )

**Comment by frankrousseau** [comment]
I think that some fixes were pushed for the Ameli konnector. Do you still face this issue?

**Comment by jeekajoo** [comment]
I don't.
Thank you
