### ISSUE TITLE
Improve discovery

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#224]
Requested [on the forum](https://forum.cozy.io/t/konnectors-ical-feed-un-seul-calendrier-possible/2268): as number of konnectors grows, it would be nice to have ways to filter and discover them: categories, tags, search…
“il serait intéressant de les trier par catégorie (abonnement téléphonie, abonnement services Web, réseaux sociaux, applis santé, ...) et pourquoi pas d'ajouter une zone de recherche/filtre pour trouver un Konnector en particulier.”

**Comment by clochix** [comment]
A lot of suggestions for improvements in [this other thread](https://forum.cozy.io/t/konnectors-propositions-petit-prob-dimport/2303)

**Comment by poupotte** [comment]
We have now categories in new version :+1:

**Comment by clochix** [comment]
Thanks! Closing this one and going back to the forum to gather feedback.

**Comment by ZeHiro** [comment]
Well I opened this one : https://github.com/cozy-labs/konnectors/issues/696
A bit overlapping but more precise
