### ISSUE TITLE
Add captaintrain konnector

### ISSUE THREAD

**Issue by m4dz** [cozy-labs/konnectors#225]
As the with [SNCF konnector](https://github.com/cozy-labs/konnectors/pull/222), we may provide a konnector to the CaptainTrain service to retrieve bills inside Cozy.

Maybe we can ask @captaintrain team if they provide an API or a simple way the get pdf bills URL from their service :smiley:?

**Comment by ZeHiro** [comment]
The connection process i quite easy, there is a json API. To fetch the bills I remember it was a bit harder

**Comment by kosssi** [comment]
like this https://github.com/cozy-labs/konnectors/issues/178

**Comment by m4dz** [comment]
My bad, I searched for `CapitaineTrain` and `CaptainTrain`, not `Capitain Train`. Close this one as duplicate of #178.

**Comment by pierrevdk** [comment]
+1000 on this one!
