### ISSUE TITLE
Import ICS protected by a password

### ISSUE THREAD

**Issue by EtienneM** [cozy-labs/konnectors#232]
I would like to import [this](https://agenda-cas.unistra.fr/SOGo/dav/iutrs-agenda/Calendar/3853-5343F400-209-47E48F80.ics) ICS file but it is protected by a password. Would it be possible to add the password field in the configuration of the ICS feed?

**Comment by clochix** [comment]
Thanks for suggesting @EtienneM ☺

As a workaround, did you try to add the credentials in the url: https://user:password@agenda-cas.unistra.fr/…

**Comment by EtienneM** [comment]
I did not know the possibility. I tried and I am now having the same problem reported in #231

**Comment by EtienneM** [comment]
Eventually it just worked!
