### ISSUE TITLE
Ameli link bank operation

### ISSUE THREAD

**Issue by Chocobozzz** [cozy-labs/konnectors#237]
The link with the bank operation doesn't work with Ameli. 

The [identifier](https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/ameli.coffee#L184) is "A.M.E.L.I" but in my department the label of the payement in my bank is "SEPA AMELI DEPARTMENT".

The label structure is the same for all departments? Can someone else tell me what did he receive as label?

**Comment by doubleface** [comment]
And in my department it is "CPAM des Yvelines". WE have to add some kind of configuration for it.

**Comment by doubleface** [comment]
I made a fix on my github repo. It works in my case Can you try it ? 

https://github.com/doubleface/konnectors.git@ameli_bank

I added a new field for the ameli connector : "Identifiant bancaire" where you can give the string used to identify ameli operations. If the field is empty, a default one is used.

If it works for you, I will do a pullrequest on the main repo

**Comment by Chocobozzz** [comment]
Yup, it works like a charm. Thanks @doubleface

**Comment by frankrousseau** [comment]
It looks fixed by last PR. Thank you for reporting.
