### ISSUE TITLE
Files is empty when opening it form Konnector

### ISSUE THREAD

**Issue by pierrevdk** [cozy-labs/konnectors#241]
When you click on "Ouvrir le dossier sélectionné" on Konnector, a new tab opens, but Files is blank.
I believe it's because the url is https://cozy-name/#apps/files/folders/ instead of https://cozy-name/#apps/files/

![capture d ecran 2016-04-29 a 15 13 47](https://cloud.githubusercontent.com/assets/3509517/14917002/2a21dcc4-0e1d-11e6-8a86-fecd200f507b.png)
![capture d ecran 2016-04-29 a 15 14 51](https://cloud.githubusercontent.com/assets/3509517/14917001/2a20642a-0e1d-11e6-8f55-eed57f789022.png)

**Comment by doubleface** [comment]
In my case, it works well and the url is withe files/folders/. Does the "/Factures" directory exist?

**Comment by pierrevdk** [comment]
Yes it does, it contains sub-folders.

**Comment by nicofrand** [comment]
I can't reproduce it either… Do you still have the issue @pierrevdk ?

**Comment by ZeHiro** [comment]
I corrected it if i remember well.

**Comment by nicofrand** [comment]
@ZeHiro Isn't this commit https://github.com/cozy-labs/konnectors/commit/836f6687ed21a560533110ac054d5bd847be7611 the one that fixed it ?

**Comment by nicofrand** [comment]
Duplicate of https://github.com/cozy-labs/konnectors/issues/241
