### ISSUE TITLE
Notifications not thrown anymore

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#244]
on konnector 0.6.4, the notifications are not thrown anymore.

**Comment by doubleface** [comment]
Yes, I am looking at it but did not think to create the issue

**Comment by doubleface** [comment]
If someone can try my pullrequest, it works for me but I am not sure it fixes all cases.

**Comment by frankrousseau** [comment]
It looks fixed. @ZeHiro can you confirm?

**Comment by ZeHiro** [comment]
Yes. Experiencing other notification problem though (i'll open another ticker)
