### ISSUE TITLE
When an import does not provide new data at notification is still raised

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#250]
It happends for ical connector and doctolib connector. Same with free.

**Comment by doubleface** [comment]
And same with SFR or ameli. I Will look at it since this is probably due to my notification fix

**Comment by ZeHiro** [comment]
@doubleface 
The problem is still here on manual fetch

I think it is here : 
https://github.com/cozy-labs/konnectors/blob/20912f900bf788dccc613cd71cbd4b22a9730098/server/controllers/konnectors.coffee#L94

**Comment by doubleface** [comment]
Yes, you are right, I fixed this this week end but could not finish it because it raised another problem with localization. I may update the pullrequest later this week (if I get the time to do  it...).

**Comment by ZeHiro** [comment]
@doubleface I took care of that

**Comment by doubleface** [comment]
Thank you for that @ZeHiro !
