### ISSUE TITLE
Uber konnector

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#302]
Fetch bills
Rides?

**Comment by frankrousseau** [comment]
Both ;)

**Comment by ZeHiro** [comment]
For the rides, we need to define a new docType (trip?).

**Comment by roukydesbois** [comment]
Hello guys,
For your information, I started such a konnector after the "tech meetup", but I haven't done a lot on it or found time to continue yet. Here it is, feel free to use/inspire/ignore ;)
https://github.com/roukydesbois/konnectors/blob/master/server/konnectors/uber.js

**Comment by ZeHiro** [comment]
I'll use you code ;)

**Comment by frankrousseau** [comment]
About the doctype maybe that `Path` could be a good type. With a `type` field that could allow values like *trip*, *running*, *biking*, etc.
