### ISSUE TITLE
Blank page when I click on "Open the selected folder"

### ISSUE THREAD

**Issue by pierrevdk** [cozy-labs/konnectors#330]
When I click on "Open the selected folder" and the folder doesn't exist yet, the url shouldn't be https://mycozy.cozycloud.cc/#apps/files/folders/ but https://mycozy.cozycloud.cc/#apps/files/

When I got to https://mycozy.cozycloud.cc/#apps/files/folders/ I end up on a blank page

**Comment by ZeHiro** [comment]
@pierrevdk I guess from what you said that the folder is not yet set. I see where the problem is. I'll fix this.
