### ISSUE TITLE
Podcast konnectors error

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#354]
From the forum 
This error is thrown when truingto import this feed : 

http://radiofrance-podcast.net/podcast09/rss_10177.xml
@babolivier 
```
/usr/local/cozy/apps/konnectors/build/server/konnectors/podcast.js:232
          throw _iteratorError2;
          ^

ReferenceError: name is not defined
    at /usr/local/cozy/apps/konnectors/build/server/konnectors/podcast.js:218:29
    at /usr/local/cozy/apps/konnectors/build/server/models/folder.js:20:12
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/model.js:213:18
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/cozymodel.js:294:18
    at parseBody (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

```

**Comment by babolivier** [comment]
Yup, that's part of the changes that broke the connector just before it was published (basically almost all the changes in https://github.com/cozy-labs/konnectors/commit/87a65fdf41e3d47672e18c6730af557c8f92dd94, excepted the merge stuff in the locales files). I'll try to find some time to fix it, but as I was supposed to be finished with this connector, I can't promise to do it very soon.

**Comment by ZeHiro** [comment]
@babolivier 
This problem could also occur due to the fact that the docType "Track" is not declared in the authorisations of package.json

**Comment by babolivier** [comment]
Yep, there's that error too, that @frankrousseau has already taken care of in #355. This PR should be merged soon, I guess.

**Comment by frankrousseau** [comment]
I published a 0.7.0 version of Konnectors. Can you check if everything is right?

**Comment by babolivier** [comment]
Works on my side! :clap:

**Comment by pololasi** [comment]
It works on my side too.
Import of about 150 podcasts in progress
[http://radiofrance-podcast.net/podcast09/rss_10177.xml](url)

**Comment by nicofrand** [comment]
This issue seems fixed now.
