### ISSUE TITLE
Record the maintainer of connectors

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#363]
Sometimes the connectors are broken due to an update of the website. It could be interesting to have a table/list linking the connectors to their developper to be able to easily warn the developper that an update is required

**Comment by Chocobozzz** [comment]
Agreed. Moreover, would it be possible to use the "Cozy statistics" to try to automatically notice when a konnector seems broken?

**Comment by frankrousseau** [comment]
What do you mean by Cozy statistics?

**Comment by ZeHiro** [comment]
@frankrousseau I think he means using your server to monitor the konnectors' status

**Comment by Chocobozzz** [comment]
@ZeHiro :+1:

@frankrousseau For example catch the exceptions/status of Konnectors from the [test servers](https://cozy.io/fr/try-it/?from=home)? It's just an idea, maybe there are other interesting tracks to explore but I think it would be a very useful feature to help developers to maintain their konnectors.

**Comment by frankrousseau** [comment]
Ok, I understand better now. But how could we check? It would require fake accounts on each services.

**Comment by frankrousseau** [comment]
Before going further, I think we should make the contributor list. What do you think about it?

**Comment by Chocobozzz** [comment]
I agree, something like @ZeHiro said :+1:

For the check, I would imagine a "report error" popup (or another thing) that would report anonymously the status code/error to a collector server. This server would analyze the datas and report an anormal amout of errors for a particular konnector.

But maybe this is not the relevant issue to discuss that?

**Comment by frankrousseau** [comment]
Yep let's open another issue!

**Comment by nicofrand** [comment]
The Readme now allows to specify the maintainer(s) of each konnector.
@ZeHiro, @doubleface, @Chocobozzz, could you write your name/pseudo for the konnectors your support ?

**Comment by ZeHiro** [comment]
capitaine train, doctolib, free mobile, free

**Comment by SomeAverageDev** [comment]
hi,
APRR and Vente-privee for me !

**Comment by nicofrand** [comment]
We still need to know who maintains (or at least created so that we can ask a question if we do not understand the code) the following konnectors:

* Bouygues box
* Bouygues Mobile
* Github
* SFR box
* Jawbone
* Nest
* Withings
* Github
* Twitter
* ical feed
* Rescue time
* Google events

@clochix Could you tell us which are maintained by the cozy team please ? RescueTime at least seems to have been developed by several members of the team.
