### ISSUE TITLE
Create SoYouStart EU application tokens

### ISSUE THREAD

**Issue by Chocobozzz** [cozy-labs/konnectors#371]
The SoYouStart EU konnector does not work yet because it does not have application tokens.

If you have a SoYouStart EU account, you can create the application tokens to make this konnector work for everyone!

**URL:** https://eu.api.soyoustart.com/createApp/
**Application name:** Cozy Cloud - Konnectors
**Application description:** Import data in your Cozy

**File:** https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/soyoustart_eu.coffee

Thanks :)

**Comment by Darcidride** [comment]
Hi,

I've a EU SoYouStart account, so I generated a key for Cozy, but im a little afraid about the informations you need, can you confirm me there are no danger to give you this informations ? 

The two following informations you need afraid me : 
- appKey: 'XXX'
- appSecret: 'XXX'

Here is the full API : https://eu.api.soyoustart.com/console/#/

**Comment by Darcidride** [comment]
Up, nobody can tell my if it's dangerous, i'm ready to give you the connector informations if you can assure me it's not dangerous... :)

**Comment by Chocobozzz** [comment]
Hi @Darcidride,

Sorry for the long wait :) I don't see any potential danger to share the keys. In the most worst case somebody else would "steal" the key credentials to abuse the OVH API but in this case your tokens would be simply revoked.

I [created applications keys](https://github.com/cozy-labs/konnectors/commit/b97804fd88f3cba2310fa9bd3a366f66b67e5db1) from my personal account and I still do not have any problem :)

**Comment by Darcidride** [comment]
Ok, taht feels good to me.. Thank you for the answer.

I updated my first post with the needed informations.

**Comment by Darcidride** [comment]
Here is the PR : https://github.com/cozy-labs/konnectors/pull/643

**Comment by Darcidride** [comment]
Well, i will psot this here because i just did the 0.7.9 update of the Konnector and actually still can't use the SoYouStart_EU konnector :
![](http://i.imgur.com/h2TB3QO.png)
The field URL is empty

**Comment by ZeHiro** [comment]
@Darcidride 
You have all the information in the error message :) .
You need, either to stop/start Konnectors or disconnect from your cozy

**Comment by Darcidride** [comment]
@ZeHiro 
Thank you to answer me like a noob :)

But in fact, I didn't detailed that I already disconnected/reconnected me and also rebooted the Cozy stack. I still have this message, and this message was already here before the update.
