### ISSUE TITLE
Missing folder for import of SNCF bills

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#376]

**Comment by Chocobozzz** [comment]
SNCF bills don't have PDF. Maybe we could add the e-ticket (if it exists) but for me it's not a bill file.
In another hand, if we do this we could then add a link in the event description to the e-ticket file.

If there are no e-ticket, I don't think it's possible to have a PDF bill.

**Comment by ZeHiro** [comment]
The konnectors says : 
Importez vos factures et événements SNCF dans votre Cozy.

**Comment by ZeHiro** [comment]
@Chocobozzz So this Konnector just imports 'nothing' (apart from the events)?

**Comment by Chocobozzz** [comment]
It imports bills that don't contain a PDF link: https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/sncf.js#L120 (`pdfurl` is just not set).

**Comment by ZeHiro** [comment]
OK. Maybe the text of the Konnector should tell this, as some people expect a real bill :)

**Comment by ZeHiro** [comment]
I close
