### ISSUE TITLE
Ameli konnector is broken

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#378]
According to [this thread](https://forum.cozy.io/t/app-konnectors/1176/20), the website has been updated and the konnector is unable to fetch the bills.
Ping @Gara64

**Comment by Gara64** [comment]
I gave a check to fix the konnector, but turns out the Ameli's website is now using generated html, so we cannot parse it as easily...

**Comment by nicofrand** [comment]
What do you mean by generated ? On the client side ? If that's the case I
guess a xhr request is made to fetch the bills..

Le mar. 6 sept. 2016 22:43, Paul Tran-Van <notifications@github.com> a
écrit :

**Comment by Gara64** [comment]
Yes, as a result, I just get the javascript after a request on the bill's page. So I don't see how to retrieve the bills, except by using a phantomjs-based trick, but maybe there is a simpler way?

**Comment by nicofrand** [comment]
You would have to watch the network panel in your browser devtools to see
which request fetched the data that will then be displayed by the
JavaScript.

Le mar. 6 sept. 2016 23:01, Paul Tran-Van <notifications@github.com> a
écrit :

**Comment by Gara64** [comment]
Yep, my bad... I've just created #470 to fix the issue.
