### ISSUE TITLE
eslint-config-airbnb not compatible with eslint 3

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#387]
This causes breaks in Travis and on developpers machines

**Comment by nicofrand** [comment]
I downgrade eslint to ^2.9.1 in https://github.com/cozy-labs/konnectors/pull/380

**Comment by ZeHiro** [comment]
yse @nicofrand 
But this idea of this issue is to find a correct way to manage the issue : delete eslint-config-airbnb? And then rewrite a set of rule for the linter. This could be a possibility.

**Comment by Chocobozzz** [comment]
Related to https://github.com/airbnb/javascript/issues/936.

I prefer to keep using airbnb rules instead of writing custom rules. Airbnb rules are well argumented and used by a lot of JS developers which would ease new contributions.

**Comment by ZeHiro** [comment]
Aidrbnb updated their eslint config to 10.0 now compatible with eslint 3.x
