### ISSUE TITLE
In the konnector, having a link to the website connected

### ISSUE THREAD

**Issue by Zykino** [cozy-labs/konnectors#403]
I was curious about the SNCF konnector and after some search in the source code I found that the konnector was designed to use http://www.voyages-sncf.com data and not http://www.sncf.com ones.

So I think, for the standard user, it will be better to click somewhere and see if it's the website he was thinking of.

There can be the same problem with localized website (OVH EU/US/...) or website with similar name (and tired peoples: https://www.showroomprive.com / https://vente-privee.com)
_ex:_ the user can't connect to his account
he follow the link and see he cannot connect to the website / he thought of an other website
he do not stay half an hour asking himself why he can not connect :)

**Comment by ZeHiro** [comment]
Konnectors usually have vendorLink property, it is then easy to displayy this information to the user.
