### ISSUE TITLE
Do not call the callback twice if File.isPresent fails somehow

### ISSUE THREAD

**Issue by bnjbvr** [cozy-labs/konnectors#427]
@nicofrand noticed on IRC that if there's an error in this code path, then the callback is called twice. https://github.com/cozy-labs/konnectors/blob/master/server/models/file.coffee#L40

**Comment by ZeHiro** [comment]
`callback err if err` should be `return callback err if err`

**Comment by ZeHiro** [comment]
Also
https://github.com/cozy-labs/konnectors/blob/master/server/models/folder.coffee#L26 
err not caught (folders could be undefined)

**Comment by ZeHiro** [comment]
Error not caught

https://github.com/cozy-labs/konnectors/blob/master/server/models/cozy_instance.coffee#L24
