### ISSUE TITLE
Forbid names with dots

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#437]
The connector's name is used to display the connector's icon by creating a class with the same name.
Therefore, if the name is "foo.bar" the class is "foo.bar" too which then gives ".foo.bar" in CSS, which is invalid.

We should forbid the dots in connectors names and add a test to for it.

**Comment by ZeHiro** [comment]
the use of cozy-slug every where should prevent this

**Comment by nicofrand** [comment]
I doubt cozy-slug replaces "." ?

**Comment by ZeHiro** [comment]
https://github.com/cozy/cozy-slug/blob/master/main.js#L355

**Comment by nicofrand** [comment]
My bad, I did not see it. Weel then, maybe cozy-slud IS used everywhere :D

**Comment by ZeHiro** [comment]
maybe. At least we should add a test for this specific case to ensure if the slug contains a dot, it is removed (same is there is no slug).
