### ISSUE TITLE
Error not localized

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#444]
After an error while fetching the token with the numericable's connector, in a cozy in French, the following message appears:

> Une erreur est survenue lors de la dernière importation : error occurred during import.

The error is thrown at this line : https://github.com/cozy-labs/konnectors/blob/master/build/server/konnectors/numericable.js#L98.

The locale key exists though : https://github.com/cozy-labs/konnectors/blob/master/client/app/locales/fr.coffee#L51.

**Comment by nicofrand** [comment]
https://github.com/cozy-labs/konnectors/blob/master/build/server/konnectors/numericable.js#L111 is not localized either.

**Comment by nicofrand** [comment]
Same with :

`Une erreur est survenue lors de la dernière importation : bad credentials`

**Comment by ZeHiro** [comment]
On a du peter un truc. Ça marchait avant.

**Comment by nicofrand** [comment]
It's only the case just after the import. If we reload the page, the message is correctly translated.

**Comment by ZeHiro** [comment]
https://github.com/cozy-labs/konnectors/blob/master/client/app/views/konnector.coffee#L412

should be :  `@showErrors t errorMessage`

**Comment by nicofrand** [comment]
Message not localized here : https://github.com/cozy-labs/konnectors/blob/master/client/app/views/konnector.coffee#L412
