### ISSUE TITLE
Specify node version in package.json

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#454]
https://docs.npmjs.com/files/package.json#engines

Could prevent weird PR from @greenkeeperio-bot

**Comment by ZeHiro** [comment]
Could also include node 0.10 in travis.yml

**Comment by nicofrand** [comment]
Seems like 0.10 was removed from tavis.yml: https://github.com/cozy-labs/konnectors/commit/3de50cabaad8c7df1acb9841253c6287c3238271
