### ISSUE TITLE
inconsistency between translation keys in konnectors and in locale file

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#455]
FB Events konnector uses : notification event**_s_** updated
Locales use : notification event updated
This should be harmonized

**Comment by nicofrand** [comment]
Should be the plural form IIRC since commits, tweets and bills are in the
plural form. What about other events-related connectors ?

Le mar. 16 août 2016 19:40, Antoine BOSSY <notifications@github.com> a
écrit :
