### ISSUE TITLE
Konnector for EDF

### ISSUE THREAD

**Issue by AradrinCozy** [cozy-labs/konnectors#456]

**Comment by ZeHiro** [comment]
What data would you like to fetch?

**Comment by AradrinCozy** [comment]
First, the bills make sense, but also the contracts and "Attestation de contrat", and of course dates for the next bills (relations with calendar and kresus ?).

**Comment by ZeHiro** [comment]
The match bills/kresus can easily be done (everything is in konnectors to achieve this). For the rest it is up to the developper 😊

**Comment by nicofrand** [comment]
I don't have any EDF account but if other connectors could create an event
for the next bill, that might be a good idea ! That would require to be
able to choose the calendar too though.

Le dim. 21 août 2016 12:41, Antoine BOSSY <notifications@github.com> a
écrit :

**Comment by ZeHiro** [comment]
I think i can try to do smth for this, but as i am 'mensualisé' i am not sure i have bills

**Comment by AradrinCozy** [comment]
For monthly payment, the bill is every 6 month and I think most of the customers are 'mensualisés' :)

**Comment by SomeAverageDev** [comment]
Hello,
I started to work on this a while ago. I can publish the current dev...

**Comment by SomeAverageDev** [comment]
I committed the files [edf ](https://github.com/SomeAverageDev/konnectors/blob/sad/server/konnectors/edf.js )and [leclrecdrive](https://github.com/SomeAverageDev/konnectors/blob/sad/server/konnectors/leclercdrive.js), not sure it is usefull as they are not functional yet... And I won't work on it for now (but anyone can).
