### ISSUE TITLE
Online konnector does not import anything

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/konnectors#465]
Hi,

Online konnector does not seem to import any bill. I am aware of https://github.com/cozy-labs/konnectors/issues/267, but my credentials should be ok (at least, they are the same that I use in the Online console page and it works there).

Konnectors log state:
```
[2016-09-07 16:42:02:734] info - Online.net | Import started
[2016-09-07 16:42:02:734] info - Online.net | Logging in on Online.net...
[2016-09-07 16:42:02:859] info - Online.net | Download bill HTML page...
[2016-09-07 16:42:02:960] info - Online.net | Bill page downloaded.
[2016-09-07 16:42:03:6] info - Online.net | Bill data parsed.
[2016-09-07 16:42:03:89] info - Online.net | Import finished
```

Am I the only one having this issue?

Thanks

**Comment by nicofrand** [comment]
Are you using 2FA on the Online.net side ?

**Comment by Phyks** [comment]
Nope, standard authentication with username / password.

**Comment by Chocobozzz** [comment]
I'll check this soon.

**Comment by Phyks** [comment]
Hmmm, is there something particular to do to use the updated version of Konnector?

I did a `cozy-monitor update konnectors`, and tried to run again the Online konnector, but behavior did not change.

Thanks!

**Comment by nicofrand** [comment]
Yes, you'll have to wait for the next build :).

Le jeu. 8 sept. 2016 12:14, Lucas Verney <notifications@github.com> a
écrit :

**Comment by ZeHiro** [comment]
@Phyks : will build a new version when all the issues here are closed: https://github.com/cozy-labs/konnectors/milestone/2

**Comment by Phyks** [comment]
Oh ok, thanks for the explanations!
