### ISSUE TITLE
Check that a connector's slug matches its filename

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#475]
If the connector's slug (or the name which will be slugified) is different from the filename (without the extension), the connector is rejected and will not appear in the app view.

**Comment by ZeHiro** [comment]
https://github.com/cozy-labs/konnectors/blob/master/server/lib/base_konnector.js#L21

When using base_konnector, the slug is set based on the name provided inside the connector

**Comment by nicofrand** [comment]
Yep but the filename has to match it

Le lun. 3 oct. 2016 19:02, Antoine BOSSY <notifications@github.com> a
écrit :
