### ISSUE TITLE
No Ability to import Google Contact

### ISSUE THREAD

**Issue by aafrey** [cozy-labs/konnectors#482]
I'm having some difficulty importing my Google contacts with the konnector. I'm using a self hosted (pi2) Cozy instance and when I try and setup the import there are a few issues. 

Issue one:
The "Connect your Google Account" button does not trigger anything. In order to get my authorization code I had to pull the auth URL by inspecting the element with dev-tools. 

Issue two:
Once I have my auth code, there is no place to paste it. No input exists on the page to paste the auth code.

There are a few errors in the console, but I don't know if they are related. The following is the one that looks the most pertinent

`Refused to display 'https://www.google.com/contacts/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

Thanks

**Comment by nicofrand** [comment]
Thanks for reporting the issue ! 

I can indeed reproduce the button issue, maybe the auth code input is linked…

**Comment by nicofrand** [comment]
JS error in the console:

```console
VM201 googlecontacts:3 Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by nicofrand** [comment]
Maybe fixed in https://github.com/cozy-labs/konnectors/commit/412be16d45d2d58ea110bf9ee333438be052328d, will have to test.

**Comment by nicofrand** [comment]
For the iframe error, this is another issue, I will open a ticket for it.

**Comment by aafrey** [comment]
Thanks @nicofrand !

**Comment by nicofrand** [comment]
Fixed by https://github.com/cozy-labs/konnectors/commit/b320a1c47a30b121a5134fc571b38184f1ab5567.

You'll have to wait for the next build though.
