### ISSUE TITLE
Vendor links should be opened in a new tab/window

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#483]
Following the error in https://github.com/cozy-labs/konnectors/issues/482#issue-177302373, we can see that konnectors opened the vendor link in the iframe (so, inside cozy) which threw an error since Google refuses to be read in an iframe.

Maybe we should force the link to be opened in a new window (target _blank) ?

**Comment by ZeHiro** [comment]
I totally aggree. All the "external links" should open a new tab/window
