### ISSUE TITLE
Dependencies incompatible with npm 3

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/konnectors#500]
Hi,

I tried to run the lint tools in this repo. First, `npm install` results in "UNMET PEER DEPENDENCY":

``` bash
$ npm run install
[…]
├─┬ eslint-config-airbnb@10.0.0
│ ├── eslint-config-airbnb-base@5.0.3
│ └── UNMET PEER DEPENDENCY eslint-plugin-import@^1.13.0
├── UNMET PEER DEPENDENCY eslint-plugin-import@^1.12.0
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^2.0.1
├── UNMET PEER DEPENDENCY eslint-plugin-react@^6.0.0
```

And then, as expected, the `npm run lint` command fails:

> ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:
> […]

I quickly tried to solve it, but without success :/

**Comment by nicofrand** [comment]
I had some warnings but that's all…
Which version of npm do you have ? I guess 3+ ?

**Comment by Phyks** [comment]
Indeed, I am using [npm 3.10.8](https://www.archlinux.org/packages/community/any/npm/) :/

I tried to manually install the required modules and was willing to push an updated package.json but, it is not working:
> npm WARN eslint-config-airbnb@10.0.0 requires a peer of eslint-plugin-import@^1.12.0 but none was installed.
> npm WARN eslint-config-airbnb-base@5.0.3 requires a peer of eslint-plugin-import@^1.13.0 but none was installed.
