### ISSUE TITLE
OVH Bills

### ISSUE THREAD

**Issue by frankrousseau** [cozy-labs/konnectors#54]
A konnector to download OVH bills.

**Comment by nicofrand** [comment]
It looks like there is an API for that: https://api.ovh.com/console/#/me/bill#GET

**Comment by frankrousseau** [comment]
I didn't see that! Thank you.

**Comment by Chocobozzz** [comment]
WIP

**Comment by frankrousseau** [comment]
Wow

**Comment by brouberol** [comment]
Can this issue be closed?
