### ISSUE TITLE
Undefined attribute on login fields

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#557]
When using the browser devtools element inspector on a connector's login field we can see an "undefined" attribute.

**Comment by nicofrand** [comment]
https://github.com/cozy-labs/konnectors/blob/master/client/app/views/konnector.coffee#L301
https://github.com/cozy-labs/konnectors/blob/master/client/app/views/konnector.coffee#L235

**Comment by ZeHiro** [comment]
It is client side bug. I close
