### ISSUE TITLE
iCalFeed does not do deduplication correctly

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/konnectors#566]
Hi,

On the following minimal iCalendar file:

```
BEGIN:VCALENDAR
BEGIN:VEVENT
SUMMARY:Voyage à Naples
DTSTART;VALUE=DATE-TIME:20161118T150000Z
DTEND;VALUE=DATE-TIME:20161120T210000Z
DESCRIPTION:
LOCATION:Italie
END:VEVENT
END:VCALENDAR
```
deduplication is not working and a new event is created at each import.

Looks similar to https://github.com/cozy-labs/konnectors/issues/235 but imported events look weird in the Databrowser:
<img width="1670" alt="capture d ecran 2016-11-02 a 11 44 28" src="https://cloud.githubusercontent.com/assets/3856586/19935836/d4b00e6a-a0f1-11e6-907d-0303c1b5f1cd.png">

**Comment by ZeHiro** [comment]
The problem here is the fact that the caldavuri is changed by the provider. We could add a more "dirty way" to do that (bydate etc)

**Comment by Phyks** [comment]
Indeed. There are also some others problems in the picture, although they are minor ones:
* first line is nonsense.
* created (and uid, not sure if it matters) are not set

I tried to track the `caldavuri` origin, but without success for now.

**Comment by Phyks** [comment]
Ok, problem is that my initial feed does not have a `UID` set on the `VEVENT`. This should not be valid according to [this doc](http://www.kanzaki.com/docs/ical/uid.html). Not sure then, if we want to support such feeds?

Still, my events get a `caldavuri`, which should be the `uid`. As `uid` is missing, I am not sure where they get this from.
