### ISSUE TITLE
SVG icon is broken

### ISSUE THREAD

**Issue by sylvaindeloux** [cozy-labs/konnectors#581]
The SVG icon file `/api/applications/konnectors.svg` is found, but not valid.

![capture d ecran 3](https://cloud.githubusercontent.com/assets/517622/20236292/fd246394-a8af-11e6-844f-8d907848e844.png)

**Comment by nicofrand** [comment]
Thanks for reporting, this should be fixed by now. Please comment here is that's not the case for you.
