### ISSUE TITLE
Magic Folder does not work

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#598]
@m4dz : 
the folder not created
the folder always selected even if another folder is selected.

Currently this is not usable as such.

**Comment by ZeHiro** [comment]
and using the slug to create th folder is not really smart as in some cases, the slug is 'dirty' compared to the name of the provider.

**Comment by m4dz** [comment]
Hi @ZeHiro !

#602 fix the issue with the select value w/ the magic folder. I invoke @poupotte about the use of konnector name instead of the slug for the folder name :)

**Comment by ZeHiro** [comment]
I now does work.
