### ISSUE TITLE
Add instructions to twitter konnector

### ISSUE THREAD

**Issue by arthurlutz** [cozy-labs/konnectors#60]
The twitter konnector probably needs a bit of context, I couldn't  easily find a way to add an application to get the consumer key etc. 

By the way, it feels a bit heavy to have to create an app (which I personnaly can't since I don't have a mobile phone setting in my twitter account) to be able to access the data. Could there be a cozy provided app ? Or is that a problem as far as privacy is concerned ? In my case the data harvested is all public I think.

**Comment by frankrousseau** [comment]
Twitter doesn't allow to connect to its API without an app. That's why we create one. Grabbing data through scrapping is heavy too.
