### ISSUE TITLE
UI issue when adding and removing accounts

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/konnectors#613]
Hi,

* Open a konnector panel, fill in the fields.
* Click "Add an account", you have two accounts, one with the fields filled in, one with empty fields
* Click "Remove last account", the first one (with the filled fields) is removed, and there is only the one with the empty fields remaining.

I would have expected the "last account" to be the "last added one", at the bottom of the page, and then keep the fields I already filled.

Not sure it is worth fixing it though, considering the rewrite of the UI to be coming.

**Comment by ZeHiro** [comment]
We are definitly on a 'won't fix' here. New client will be released by the end of december.

**Comment by Phyks** [comment]
Sure, NP.
