### ISSUE TITLE
Free Mobile bills

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#62]
I already have a first version working fine, but : 
- Code is ugly (spaghetti inside)
- Maybe some steps are not required (the auth sequence on the wesite is a pain in the ass)
- Code is ugly (not sure it is state of the art coffeescript) 
- It adds a new dependency (due to the need to decode png keyboard)
- It is full of console.log (blabla)
When I have reworked it, I'll create a pull request

**Comment by ZeHiro** [comment]
Can be closed. The konnector works fine.

**Comment by frankrousseau** [comment]
Thx
