### ISSUE TITLE
Write a tutorial explaining how to create a connector

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#65]
Writing a connector is not very hard, but documentation is missing. Writing a tutorial would encourage people needing other connectors to write them themselves, with our help.

**Comment by frankrousseau** [comment]
You're definitely right.

**Comment by frankrousseau** [comment]
Done:

https://github.com/cozy-labs/konnectors/wiki

**Comment by kosssi** [comment]
:+1:
