### ISSUE TITLE
Wrong year in filenames for Ameli Konnector

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#655]
A user reports that a bill from the 22th december 2016 was imported as 20171222 in its filename.
This is due to https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/ameli.coffee#L147 that automatically selects the current year (since it is not provided by the website itself) without checking that this date is not superior to the current date.

**Comment by ZeHiro** [comment]
Closed by #664
