### ISSUE TITLE
[free] 'bad credential' not raised

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#68]
When the credential are bad (wrong login)

- no 'err' in the request
- a 'res.headers.location' is defined (something like /login/login.pl?login=TRYED_LOGIN&error=1)
- res.statusCode = 302

A check over the location structure (find 'error' in it) as an extra condition would fix this.
I will propose a fix soon.

**Comment by frankrousseau** [comment]
Fixed by @ZeHiro
