### ISSUE TITLE
Impossible to import data when 'bad credential' is raised

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#71]
This bug appears in free and free mobile konnectors : 
use bad credential (non empty fields) 
try to import bills
'bad credential' is raised
use good credentials
try to import bills
'bad credential' is still raised (based on the time it takes before the error is raised, the error is raised at the beginning of the fetcher)

Restarting konnectors is necessary to import bills.

**Comment by frankrousseau** [comment]
Do you still face that issue @ZeHiro?

**Comment by ZeHiro** [comment]
I am not sure, I have good credentials now :p. But it wa fixed long time ago.
