### ISSUE TITLE
Konnectors doesn't check if the default import path exists

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#728]
I've just tried to import a podcast feed.
I'm now unable to ind the files inside the Files tree.
After digging inside the database, I found that the files have been imported into folder `/Mes Comptes/Podcast/`. But neither `/Mes Comptes/` nor `/Mes Comptes/Podcast/` folders exist, so, or now, I'm unable to access my files from the files application.

**Comment by ZeHiro** [comment]
It is a "bug" from the podcast konnector. An easy way to fix this is to manually create the folders, the files will appear by magic

**Comment by clochix** [comment]
Yes, as a long time Cozy user, I know I can just create the missing folders. But this may not be a user friendly experiment for newcomers ;-)

**Comment by ZeHiro** [comment]
Of course, i'll propose a fix for the konnector. It really is nothing to fix.

**Comment by ZeHiro** [comment]
in fact it is a duplicate pf https://github.com/cozy-labs/konnectors/issues/706
I close.
