### ISSUE TITLE
Click on konnector icons has no effect (old browser)

### ISSUE THREAD

**Issue by jacquarg** [cozy-labs/konnectors#732]
From a tester of MesInfos, (of the Maif team) : https://mesinfos.fing.org/forum/d/50-probl-me-d-acc-s-li-la-nouvelle-version-de-my-accounts

It looks to occurs on Chrome 42 or IE 10, but they are the only browsers that Maif employes can use at their work !!

**Comment by goldoraf** [comment]
These browsers don't support `Object.assign` which we use in the app. This PR should fix the problem: https://github.com/cozy-labs/konnectors/pull/733

**Comment by jacquarg** [comment]
Really sorry, but similar problem with Firefox 45 ... 
Clicking on not-connected Konnector do nothing, and throw errors (not route matching ... ) in console.

This is problematic because Firefox 45 is (with IE11) the navigator on Orange teams desktops. But it could be the one for a lot of big companies, because it's the ESR version of firefox ( https://www.mozilla.org/en-US/firefox/organizations/faq/ ) : Extended Support Release ; and it will be the ESR version up to 2018 (and the 58th version).

What do you think of trying to make My Account compatible with FIrefox ESR version in the future ? (I m developer, I know it's a boring question ; )
