### ISSUE TITLE
Free konnector broken

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#75]
https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/free.coffee#L102
and L103
These lines should be : 
        isError = res.headers.location? and
            res.headers.location.indexOf("error") isnt -1

**Comment by ZeHiro** [comment]
I'll propose a PR for this issue and for a fix for freemobile connector

**Comment by frankrousseau** [comment]
Ok thank you. It's probably a mistake I did in my last merge.
