### ISSUE TITLE
Allow to use several accounts of a single konnector

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#91]
A user asks for this possibility on the forum, as it has a pro and a personal account at the same provider:

https://forum.cozy.io/t/konnectors-2-comptes-pour-un-meme-service/933/1

**Comment by kosssi** [comment]
:+1:

**Comment by frankrousseau** [comment]
Thank you for reporting.

**Comment by clochix** [comment]
This is also requested for the ICAL connector, see #219

**Comment by ZeHiro** [comment]
As of 0.6.2 this is done. Thanks
