### ISSUE TITLE
[Free Mobile]  Make the difference between sevel phone numbers for the same account

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#92]
Support multi line (several phone numbers for one account). Use the "phone numbre" to make the difference.

**Comment by f6fvy** [comment]
I'm in that use case, and currently there a 2 different pdf files imported : One for the detailed phone bill of the "master number" of the account, and another one which is the summary of the various attached phones numbers. **But** these two files have the same name in the files app, which is kind of disturbing !

**Comment by ZeHiro** [comment]
OK. I will make an update of the konnector, I wait for some other fixes to implement it in a clean way. Can you describe me what files are listed on the webpage? And if it is necessary to import all of them? I only have one line attached to my free mobile account. 
When the update is made, could you then test-it?

**Comment by frankrousseau** [comment]
Thank you for reporting.
