### ISSUE TITLE
When there is no icon available, the first one in the list is used

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#99]
In 0.3.2, the first icon in the list is Bouygueś. Shouldn't this be the Konnectorś icon?

**Comment by cylwin** [comment]
Seems to be fixed here : 
https://github.com/cozy-labs/konnectors/commit/7943869d0ced76ef331ddba5f8b1315a67f85e07

**Comment by frankrousseau** [comment]
Yes, it's fixed. Is it ok for you @ZeHiro?

**Comment by ZeHiro** [comment]
Well, I cannot try, all konnectors now have a icon :) I need to try with a new konnector. I'll let you know when I do.
